### ISSUE TITLE
How to configure continuous action space with value ranges in common.yaml?

### ISSUE THREAD

**Issue by zxzxsx** [ucd-dare/CarDreamer#23]
Thank you for your great work! I'm trying to modify the action space configuration in `common.yaml` to use continuous values instead of discrete ones. Could you please advise:

1.What parameters should I modify in `common.yaml` to change the action space type to continuous?
2.How can I specify valid value ranges (minimum/maximum bounds) for these continuous actions?

Specifically, I want to:

1.Change action space from discrete to continuous
2.Define numerical bounds for each action dimension (e.g., [-1.0, 1.0] or [0.0, 5.0])

Would it be something like this? (Please correct if wrong)

  ```
action:
    discrete: False # whether to use discrete control space
    continuous_acc: [-2.0, 2.0] # continuous value of accelerations
    continuous_steer: [-0.6, 0.6] # continuous value of steering angles
    n_commands: 3 # number of text commands
```
